from __future__ import annotations

from dataclasses import asdict, dataclass
from hashlib import sha256
from pathlib import PurePosixPath
import ast
import json
import re
import statistics
from typing import Any, Mapping

from .code_generation import FCACodeGenerator, ProgramIR


class RepositoryGenerationError(RuntimeError):
    """Raised when FCA cannot safely form a repository change candidate."""


@dataclass(frozen=True)
class RepositoryEditCandidate:
    path: str
    operation: str
    before_sha256: str
    after_sha256: str
    content: str
    checks: tuple[str, ...]

    def to_dict(self, *, include_content: bool = False) -> dict[str, Any]:
        data = asdict(self)
        if not include_content:
            data.pop("content", None)
        return data


@dataclass(frozen=True)
class RepositoryGenerationResult:
    version: str
    state: str
    plan_id: str
    goal: str
    repository_digest: str
    target_path: str
    edits: tuple[RepositoryEditCandidate, ...]
    checks: tuple[str, ...]
    errors: tuple[str, ...]

    @property
    def ok(self) -> bool:
        return self.state == "generated_candidate" and not self.errors

    def to_dict(self, *, include_content: bool = False) -> dict[str, Any]:
        return {
            "version": self.version,
            "state": self.state,
            "plan_id": self.plan_id,
            "goal": self.goal,
            "repository_digest": self.repository_digest,
            "target_path": self.target_path,
            "edits": [
                edit.to_dict(include_content=include_content) for edit in self.edits
            ],
            "checks": list(self.checks),
            "errors": list(self.errors),
        }


class FCARepositoryGenerator:
    """Pure repository-level candidate generation built on FCA ProgramIR.

    Input is an inert path->text snapshot. Output is an in-memory set of file
    edits with pre/post hashes and static validation evidence. This class never
    touches the filesystem, invokes subprocesses, calls git, opens a branch, or
    promotes a candidate.

    V2 can create a generated Python module plus a focused unittest. It may
    replace an existing target only when that file carries FCA's own generated
    marker, preventing arbitrary full-file rewrites.
    """

    VERSION = "fca.repository_generation.v2"
    SOURCE_MARKER = "Generated by FCA bounded ProgramIR code generator"
    TEST_MARKER = "Generated by FCA repository candidate generator"
    EXPLICIT_PY_PATH = re.compile(
        r"(?<![A-Za-z0-9_./-])"
        r"([A-Za-z0-9_.-]+(?:/[A-Za-z0-9_.-]+)*\.py)"
        r"(?![A-Za-z0-9_./-])",
        re.I,
    )

    def __init__(
        self,
        *,
        code_generator: FCACodeGenerator | None = None,
        max_snapshot_files: int = 512,
        max_file_bytes: int = 300_000,
        max_total_source_bytes: int = 2_000_000,
        max_edits: int = 4,
    ) -> None:
        if not 1 <= int(max_snapshot_files) <= 10_000:
            raise ValueError("max_snapshot_files must be in [1, 10000]")
        if not 1_024 <= int(max_file_bytes) <= 2_000_000:
            raise ValueError("max_file_bytes must be in [1024, 2000000]")
        if not int(max_file_bytes) <= int(max_total_source_bytes) <= 20_000_000:
            raise ValueError("invalid max_total_source_bytes")
        if not 1 <= int(max_edits) <= 8:
            raise ValueError("max_edits must be in [1, 8]")
        self.code_generator = code_generator or FCACodeGenerator()
        self.max_snapshot_files = int(max_snapshot_files)
        self.max_file_bytes = int(max_file_bytes)
        self.max_total_source_bytes = int(max_total_source_bytes)
        self.max_edits = int(max_edits)

    def generate(
        self,
        goal: str,
        snapshot: Mapping[str, str],
        *,
        target_path: str | None = None,
        include_tests: bool = True,
    ) -> RepositoryGenerationResult:
        goal = str(goal or "").strip()
        if not goal:
            raise ValueError("goal is required")

        normalized, repository_digest = self._normalize_snapshot(snapshot)
        target = self._resolve_target(goal, target_path)
        test_path = self._test_path(target)

        if target in normalized and self.SOURCE_MARKER not in normalized[target]:
            return self._rejected(
                goal,
                repository_digest,
                target,
                "existing_target_not_fca_generated",
            )
        if include_tests and test_path in normalized and self.TEST_MARKER not in normalized[test_path]:
            return self._rejected(
                goal,
                repository_digest,
                target,
                "existing_test_not_fca_generated",
            )

        filename = PurePosixPath(target).name
        try:
            generated = self.code_generator.generate(goal, filename=filename)
        except Exception as exc:
            return self._rejected(
                goal,
                repository_digest,
                target,
                "program_generation_failed",
                (type(exc).__name__,),
            )
        if not generated.ok or generated.ir is None:
            return self._rejected(
                goal,
                repository_digest,
                target,
                "program_generation_failed",
                tuple(generated.errors),
            )

        source = generated.source
        source_checks, source_errors = self._validate_generated_module(source)
        if source_errors:
            return self._rejected(
                goal,
                repository_digest,
                target,
                "generated_module_static_validation_failed",
                source_errors,
            )

        edits: list[RepositoryEditCandidate] = [
            self._edit_for(
                target,
                normalized.get(target),
                source,
                checks=tuple(dict.fromkeys(generated.checks + source_checks)),
            )
        ]

        bundle_checks = [
            "snapshot_digest",
            "safe_target_path",
            "program_ir",
            "module_static_validation",
        ]

        if include_tests:
            try:
                test_source = self._emit_focused_test(target, generated.ir)
            except Exception as exc:
                return self._rejected(
                    goal,
                    repository_digest,
                    target,
                    "focused_test_generation_failed",
                    (type(exc).__name__,),
                )
            test_checks, test_errors = self._validate_test_source(test_source)
            if test_errors:
                return self._rejected(
                    goal,
                    repository_digest,
                    target,
                    "focused_test_static_validation_failed",
                    test_errors,
                )
            edits.append(
                self._edit_for(
                    test_path,
                    normalized.get(test_path),
                    test_source,
                    checks=test_checks,
                )
            )
            bundle_checks.extend(("focused_test_generated", "focused_test_static_validation"))

        if len(edits) > self.max_edits:
            return self._rejected(
                goal,
                repository_digest,
                target,
                "edit_count_exceeds_bound",
            )

        plan_id = self._plan_digest(
            goal=goal,
            repository_digest=repository_digest,
            target_path=target,
            edits=tuple(edits),
            checks=tuple(bundle_checks),
        )
        return RepositoryGenerationResult(
            version=self.VERSION,
            state="generated_candidate",
            plan_id=plan_id,
            goal=goal,
            repository_digest=repository_digest,
            target_path=target,
            edits=tuple(edits),
            checks=tuple(bundle_checks),
            errors=(),
        )

    def _normalize_snapshot(
        self,
        snapshot: Mapping[str, str],
    ) -> tuple[dict[str, str], str]:
        if not isinstance(snapshot, Mapping):
            raise TypeError("snapshot must be a path->text mapping")
        if len(snapshot) > self.max_snapshot_files:
            raise ValueError("snapshot exceeds file-count bound")

        normalized: dict[str, str] = {}
        total = 0
        for raw_path, raw_content in snapshot.items():
            if not isinstance(raw_path, str) or not isinstance(raw_content, str):
                raise TypeError("snapshot paths and contents must be strings")
            path = self._safe_path(raw_path)
            if path in normalized:
                raise ValueError("duplicate normalized snapshot path")
            size = len(raw_content.encode("utf-8"))
            if size > self.max_file_bytes:
                raise ValueError(f"snapshot file exceeds byte bound: {path}")
            total += size
            if total > self.max_total_source_bytes:
                raise ValueError("snapshot exceeds total source byte bound")
            normalized[path] = raw_content

        rows = [
            {
                "path": path,
                "sha256": sha256(content.encode("utf-8")).hexdigest(),
                "bytes": len(content.encode("utf-8")),
            }
            for path, content in sorted(normalized.items())
        ]
        digest = sha256(
            json.dumps(rows, sort_keys=True, separators=(",", ":")).encode("utf-8")
        ).hexdigest()
        return normalized, digest

    def _resolve_target(self, goal: str, explicit: str | None) -> str:
        if explicit is not None:
            path = self._safe_path(explicit)
        else:
            matches = [
                self._safe_path(match)
                for match in self.EXPLICIT_PY_PATH.findall(goal)
            ]
            path = matches[0] if matches else (
                "generated/fca_program_"
                + sha256(goal.encode("utf-8")).hexdigest()[:12]
                + ".py"
            )
        if not path.endswith(".py"):
            raise RepositoryGenerationError("repository generator v2 requires a .py target")
        if path.startswith("tests/"):
            raise RepositoryGenerationError("target module cannot be under tests/")
        return path

    @classmethod
    def _safe_path(cls, raw_path: str) -> str:
        path = str(raw_path or "").replace("\\", "/")
        posix = PurePosixPath(path)
        if (
            not path
            or posix.is_absolute()
            or any(part in {"", ".", "..", ".git"} for part in posix.parts)
            or "\x00" in path
        ):
            raise ValueError("unsafe repository path")
        normalized = posix.as_posix()
        if len(normalized) > 240:
            raise ValueError("repository path exceeds bound")
        return normalized

    @staticmethod
    def _test_path(target: str) -> str:
        stem = PurePosixPath(target).stem
        safe_stem = re.sub(r"[^A-Za-z0-9_]+", "_", stem).strip("_") or "generated"
        suffix = sha256(target.encode("utf-8")).hexdigest()[:8]
        return f"tests/test_{safe_stem}_{suffix}.py"

    def _edit_for(
        self,
        path: str,
        before: str | None,
        content: str,
        *,
        checks: tuple[str, ...],
    ) -> RepositoryEditCandidate:
        raw = content.encode("utf-8")
        if len(raw) > self.max_file_bytes:
            raise RepositoryGenerationError("generated edit exceeds file byte bound")
        return RepositoryEditCandidate(
            path=path,
            operation="modify" if before is not None else "create",
            before_sha256=(
                sha256(before.encode("utf-8")).hexdigest() if before is not None else ""
            ),
            after_sha256=sha256(raw).hexdigest(),
            content=content,
            checks=checks,
        )

    def _validate_generated_module(
        self,
        source: str,
    ) -> tuple[tuple[str, ...], tuple[str, ...]]:
        checks: list[str] = []
        errors: list[str] = []
        if self.SOURCE_MARKER not in source:
            errors.append("generated_source_marker_missing")
        else:
            checks.append("generated_source_marker")
        if len(source.encode("utf-8")) <= self.max_file_bytes:
            checks.append("module_size_limit")
        else:
            errors.append("module_size_limit")
        try:
            tree = ast.parse(source, filename="<fca-repository-module>")
            compile(tree, "<fca-repository-module>", "exec")
            checks.append("module_compile")
        except SyntaxError as exc:
            errors.append(f"module_syntax:{exc.lineno}")
        return tuple(checks), tuple(errors)

    def _validate_test_source(
        self,
        source: str,
    ) -> tuple[tuple[str, ...], tuple[str, ...]]:
        checks: list[str] = []
        errors: list[str] = []
        if self.TEST_MARKER not in source:
            errors.append("test_source_marker_missing")
        else:
            checks.append("test_source_marker")
        if len(source.encode("utf-8")) <= self.max_file_bytes:
            checks.append("test_size_limit")
        else:
            errors.append("test_size_limit")
        try:
            tree = ast.parse(source, filename="<fca-repository-test>")
            compile(tree, "<fca-repository-test>", "exec")
            checks.append("test_compile")
        except SyntaxError as exc:
            return tuple(checks), tuple(errors + [f"test_syntax:{exc.lineno}"])

        forbidden = {"eval", "exec", "compile", "__import__", "open"}
        for node in ast.walk(tree):
            if (
                isinstance(node, ast.Call)
                and isinstance(node.func, ast.Name)
                and node.func.id in forbidden
            ):
                errors.append(f"test_forbidden_call:{node.func.id}")
        if not errors:
            checks.append("test_ast_policy")
        return tuple(checks), tuple(errors)

    def _emit_focused_test(self, target: str, ir: ProgramIR) -> str:
        sample, kwargs = self._probe(ir)
        expected = self._evaluate_ir(ir, sample, kwargs)
        test_name = "test_generated_program_ir_contract"
        return f'''from __future__ import annotations

# {self.TEST_MARKER}

import importlib.util
from pathlib import Path
import unittest


TARGET = Path(__file__).resolve().parents[1] / {target!r}


def _load_target():
    spec = importlib.util.spec_from_file_location("fca_generated_candidate", TARGET)
    if spec is None or spec.loader is None:
        raise RuntimeError("could not load generated target")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class GeneratedProgramTests(unittest.TestCase):
    def {test_name}(self):
        module = _load_target()
        self.assertEqual(module.PROGRAM_IR, {list(ir.operations)!r})
        result = module.apply_program(
            {sample!r},
            needle={kwargs["needle"]!r},
            pattern={kwargs["pattern"]!r},
            old={kwargs["old"]!r},
            new={kwargs["new"]!r},
            count={kwargs["count"]!r},
        )
        self.assertEqual(result, {expected!r})


if __name__ == "__main__":
    unittest.main()
'''

    @staticmethod
    def _probe(ir: ProgramIR) -> tuple[Any, dict[str, Any]]:
        ops = set(ir.operations)
        params = dict(ir.parameters)
        if "json_numeric_keys" in ops or "json_keys" in ops:
            sample: Any = {"b": "x", "a": 1, "c": 2.5}
        elif "extract_numbers" in ops:
            sample = "alpha 12 beta 3 alpha 12"
        elif "split_lines" in ops or "filter_nonempty" in ops:
            sample = "beta\n\nalpha\nbeta\ngamma"
        else:
            sample = "alpha beta alpha"

        kwargs = {
            "needle": "alpha",
            "pattern": r"[a-z]+",
            "old": "alpha",
            "new": "gamma",
            "count": int(params.get("count", "2")) if params.get("count") != "__RUNTIME__" else 2,
        }
        return sample, kwargs

    @staticmethod
    def _evaluate_ir(ir: ProgramIR, value: Any, kwargs: Mapping[str, Any]) -> Any:
        data = value
        for op in ir.operations:
            if op == "json_numeric_keys":
                if not isinstance(data, dict):
                    raise TypeError("JSON object required")
                data = sorted(
                    str(k)
                    for k, v in data.items()
                    if isinstance(v, (int, float)) and not isinstance(v, bool)
                )
            elif op == "json_keys":
                if not isinstance(data, dict):
                    raise TypeError("JSON object required")
                data = sorted(map(str, data.keys()))
            elif op == "extract_numbers":
                if isinstance(data, (list, tuple)):
                    data = [float(x) for x in data]
                else:
                    data = [
                        float(x)
                        for x in re.findall(
                            r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)",
                            str(data),
                        )
                    ]
            elif op == "split_lines":
                data = str(data).splitlines()
            elif op == "filter_nonempty":
                data = [str(x).strip() for x in data if str(x).strip()]
            elif op == "unique":
                seen: set[str] = set()
                out: list[Any] = []
                iterable = data if isinstance(data, list) else str(data)
                for item in list(iterable):
                    key = (
                        json.dumps(item, ensure_ascii=False, sort_keys=True)
                        if isinstance(item, (dict, list))
                        else repr(item)
                    )
                    if key not in seen:
                        seen.add(key)
                        out.append(item)
                data = out
            elif op == "sort":
                data = sorted(data)
            elif op == "sort_desc":
                data = sorted(data, reverse=True)
            elif op == "head":
                data = list(data)[: int(kwargs["count"])]
            elif op == "tail":
                count = int(kwargs["count"])
                data = list(data)[-count:] if count else []
            elif op == "count_occurrences":
                data = str(data).count(str(kwargs["needle"]))
            elif op == "regex_extract":
                data = re.findall(str(kwargs["pattern"]), str(data))
            elif op == "replace":
                data = str(data).replace(str(kwargs["old"]), str(kwargs["new"]))
            elif op == "reverse":
                data = str(data)[::-1]
            elif op == "upper":
                data = str(data).upper()
            elif op == "lower":
                data = str(data).lower()
            elif op in {"sum", "mean", "median", "min", "max"}:
                if isinstance(data, (list, tuple)):
                    numbers = [float(x) for x in data]
                else:
                    numbers = [
                        float(x)
                        for x in re.findall(
                            r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)",
                            str(data),
                        )
                    ]
                if op == "sum":
                    data = sum(numbers)
                elif op == "mean":
                    data = statistics.fmean(numbers)
                elif op == "median":
                    data = statistics.median(numbers)
                elif op == "min":
                    data = min(numbers)
                else:
                    data = max(numbers)
            elif op == "word_count":
                data = len(str(data).split())
            elif op == "char_count":
                data = len(str(data))
            elif op == "line_count":
                data = len(str(data).splitlines())
            else:
                raise RepositoryGenerationError(f"unsupported IR operation: {op}")
        return data

    @staticmethod
    def _plan_digest(
        *,
        goal: str,
        repository_digest: str,
        target_path: str,
        edits: tuple[RepositoryEditCandidate, ...],
        checks: tuple[str, ...],
    ) -> str:
        payload = {
            "version": FCARepositoryGenerator.VERSION,
            "goal_sha256": sha256(goal.encode("utf-8")).hexdigest(),
            "repository_digest": repository_digest,
            "target_path": target_path,
            "edits": [
                {
                    "path": edit.path,
                    "operation": edit.operation,
                    "before_sha256": edit.before_sha256,
                    "after_sha256": edit.after_sha256,
                    "checks": list(edit.checks),
                }
                for edit in edits
            ],
            "checks": list(checks),
        }
        return sha256(
            json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
        ).hexdigest()

    def _rejected(
        self,
        goal: str,
        repository_digest: str,
        target: str,
        reason: str,
        errors: tuple[str, ...] = (),
    ) -> RepositoryGenerationResult:
        merged_errors = (reason,) + tuple(errors)
        plan_id = sha256(
            json.dumps(
                {
                    "version": self.VERSION,
                    "goal_sha256": sha256(goal.encode("utf-8")).hexdigest(),
                    "repository_digest": repository_digest,
                    "target": target,
                    "errors": merged_errors,
                },
                sort_keys=True,
                separators=(",", ":"),
            ).encode("utf-8")
        ).hexdigest()
        return RepositoryGenerationResult(
            version=self.VERSION,
            state="rejected",
            plan_id=plan_id,
            goal=goal,
            repository_digest=repository_digest,
            target_path=target,
            edits=(),
            checks=("snapshot_digest",),
            errors=merged_errors,
        )
